### PR TITLE
Adds support for 'Bucket policy only' buckets on Google Cloud Storage

### PR DESCRIPTION
**Pull request by wmuizelaar**
Fixes https://github.com/Interfacelab/ilab-media-tools/issues/93

@jawngee let me know what you think!

### CODE REVIEW

**Comment by jawngee** [comment]
I will test this out in the morning!

**Comment by wmuizelaar** [comment]
@jawngee any feedback so far? :-)

**Comment by jawngee** [comment]
I’m actually planning on merging and testing Monday.  About to drop a huge update this week (new background processing system) and am cleaning all of that up.
-- 

jon gilkison
principal, interfacelab
https://linkedin.com/in/jongilkison <https://linkedin.com/in/jongilkison>
https://github.com/jawngee <https://linkedin.com/in/jongilkison>
http://interfacelab.io/ <http://interfacelab.io/>

**Comment by jawngee** [comment]
Nice work thanks man!

**Pull request merged**
